version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: mern-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    depends_on:
      - mongo

volumes:
  mongo_data:
